hornor_guests = ['Albert', 'Jack Ma', 'Feifei Li']
print("It's very hornor to me for you coming " + hornor_guests[0])
print("It's very hornor to me for you coming " + hornor_guests[1])
print("It's very hornor to me for you coming " + hornor_guests[2])
print('I find a greater table for our dinner!')
hornor_guests.insert(0, 'Pan Pei')
hornor_guests.insert(1, 'Liao Jing')
hornor_guests.append('kiki')
print("It's very hornor to me for you coming " + hornor_guests[0])
print("It's very hornor to me for you coming " + hornor_guests[1])
print("It's very hornor to me for you coming " + hornor_guests[2])
print("It's very hornor to me for you coming " + hornor_guests[-3])
print("It's very hornor to me for you coming " + hornor_guests[-2])
print("It's very hornor to me for you coming " + hornor_guests[-1])
print('Only two guests could own the site')
out_guests = hornor_guests.pop()
print('sorry, We could offer the dinner tonight ' + out_guests)
out_guests = hornor_guests.pop()
print('sorry, We could offer the dinner tonight ' + out_guests)
out_guests = hornor_guests.pop()
print('sorry, We could offer the dinner tonight ' + out_guests)
out_guests = hornor_guests.pop()
print('sorry, We could offer the dinner tonight ' + out_guests)
print('You are Lucky!' + hornor_guests[0])
print('You are Lucky!' + hornor_guests[1])
del hornor_guests[0]
del hornor_guests[0] # Pay atention! hornor_guests[0]
print(hornor_guests)