hornor_guests = ['Albert', 'Jack Ma', 'Feifei Li']
print("It's very hornor to me for you coming " + hornor_guests[0])
print("It's very hornor to me for you coming " + hornor_guests[1])
print("It's very hornor to me for you coming " + hornor_guests[2])
print('I find a greater table for our dinner!')
hornor_guests.insert(0, 'Pan Pei')
hornor_guests.insert(1, 'Liao Jing')
hornor_guests.append('kiki')
print("It's very hornor to me for you coming " + hornor_guests[0])
print("It's very hornor to me for you coming " + hornor_guests[1])
print("It's very hornor to me for you coming " + hornor_guests[2])
print("It's very hornor to me for you coming " + hornor_guests[-3])
print("It's very hornor to me for you coming " + hornor_guests[-2])
print("It's very hornor to me for you coming " + hornor_guests[-1])
print('There are ' + str(len(hornor_guests)) + ' attendent')